### ISSUE TITLE
Updates to newest security patches and SDK's

### ISSUE THREAD

**Issue by CFlatWouldbeMinor** [IBM-Bluemix-Docs/runtimes#13]
It would be very helpful to see a roadmap and/or have buildpacks for ASP.NET Coreavailable to the latest MS versions
SDK 2.1.4 / Runtime 2.0.5
Is there any plan to update the buildpacks e.g. eu-gb.bluemix.net

**Comment by lzdanski** [comment]
Hello! 
I'll pass your feedback on to the rest of the team, thanks for reaching out to us.

(Great username, by the way!)

**Comment by carneirocorp** [comment]
Hello, how are you ?

Seems like there's no update on .net version... Microsoft has a LTS on 2.1.4 (https://www.microsoft.com/net/support/policy on 2018/09/13).  Any plans on update Bluemix servers ?

**Comment by cjcarpen** [comment]
Hi @CFlatWouldbeMinor and @carneirocorp! We updated the ASP.NET Core buildpack today - check out the updated runtime and SDK versions here: https://console.bluemix.net/docs/runtimes/dotnet/updates.html#latest_updates

**Comment by carneirocorp** [comment]
@cjcarpen great news !!! Tks a lot !
