### ISSUE TITLE
Broken links in Node.js docs

### ISSUE THREAD

**Issue by vwilburn** [IBM-Bluemix-Docs/runtimes#46]
Hello, please correct/update broken links to the starter kits. @jenschlot 

On this page, the "Using the starter applications" hyperlink is broken:
https://console.bluemix.net/docs/runtimes/nodejs/index.html#nodejs_runtime

In the left nav, links are broken: 
Using the starter applications
Using community buildpacks

**Comment by cjcarpen** [comment]
Thanks, @vwilburn ! The links within the Node.js index.html and navigation (and corresponding links in the other buildpacks) are now fixed. If you continue to see this error, please let me know.
