### ISSUE TITLE
IBM no longer produces the IBM® SDK for Node.js

### ISSUE THREAD

**Issue by tom342178** [IBM-Bluemix-Docs/runtimes#76]
I found this:
Note: IBM no longer produces the IBM® SDK for Node.js for AIX®, Linux, macOS, or Windows because IBM's contributions to the Node.js open source project mean that these packages are no longer required. For more information, see the announcement in the Node.js @ IBM developer center. 

Here: https://www.ibm.com/support/knowledgecenter/en/SSWLKB/welcome_nodesdk_family.html

If this is true the node.js buildpack docs are either false or we are running a buildpack that is no longer being maintained.

**Comment by Jhschube** [comment]
@tom342178 Does this explanation clarify things, can we close this this issue?

**Comment by Jhschube** [comment]
Closing this issue. IBM no longer produces the runtime but it does still produce the buildpack which is what is in question here. No action needed.
